### ISSUE TITLE
VIN info is not complete

### ISSUE THREAD

**Issue by nona00** [morcibacsi/psa_van_bus_packet_descriptions#1]
![grafik](https://github.com/morcibacsi/psa_van_bus_packet_descriptions/assets/3192606/6b137eed-9c63-4dff-a769-e5c78a92a0a5)

unclear if there is a checksum applied or not

**Comment by morcibacsi** [comment]
It is complete. Every message contains 2 bytes of checksum at the end. The checksum is calculated by the VAN data controller hardware which is either a TSS463 or a TSS461 chip. It is a CRC-15. There is some info regarding that here: [http://graham.auld.me.uk/projects/vanbus/crc15.html](http://graham.auld.me.uk/projects/vanbus/crc15.html)

**Comment by nona00** [comment]
Thank you very much for the information regarding the CRC.

I analyzed the VAN dumps of Graham (https://raw.githubusercontent.com/dwery/van-bus/master/bus_captures/graham/amazing2home.van) and found that there is a mismatch between the VAN data and the description on his page and the data in this repository.

VIN message: E248564633384252485A4638313532333333301ABEN.

In the documentation on http://graham.auld.me.uk/projects/vanbus/packets.html there is shown

E24 W00 564633384252485A463831353030303030 ???? N

To get it working I have to send the Header E248 ... VIN and not only E24 ...VIN.

**Comment by morcibacsi** [comment]
Although Grahams work is a huge help the packet descriptions he has isn't always accurate. Also the packet description is quite strange as he worked on the binary level of the messages. The identifier is always 3 bytes long, so the identifier of the VIN is E24 the "8" is the value of the command in the message (See the frame type without ACK in the [datasheet of the TSS463](https://www.microchip.com/content/dam/mchp/documents/OTH/ProductDocuments/DataSheets/doc7601.pdf) page 19)
![image](https://github.com/morcibacsi/psa_van_bus_packet_descriptions/assets/6507173/775bcafc-bbc7-4207-9001-07d06321d632) 
The bit at RTR is a manchester bit, so that isn't need to be concerned of.

I strongly recommend to study the various frame types from the datasheet as those are very important on the VAN bus. 
Also check my examples in the TSS463 library. For example the 8A4 is the same message type as the E24: [https://github.com/morcibacsi/arduino_tss463_van/blob/master/examples/tss463_van_dashboard_experiment/tss463_van_dashboard_experiment.ino#L67](https://github.com/morcibacsi/arduino_tss463_van/blob/master/examples/tss463_van_dashboard_experiment/tss463_van_dashboard_experiment.ino#L67)

So in general if you are trying to write on the bus with a TSS46x IC, you don't need to worry about the command field and the checksum as the hardware and the library will take care of those. However if your plan is to write some code which bitbangs the messages without a VAN controller IC... well in that case these things you need to take care of. :)

**Comment by nona00** [comment]
Thank you very much for the explanations and the datasheet. 

I will try the TSS463 library when I have all parts for building a PSAVanCanBridgeHW. 

Currently I'm using esp32_rmt_van_rx with a SN65HVD230, great work from you!
